[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tk"
path = "src/main.rs"

[dependencies]
clap = {version = "4", features = ["derive"]}
rusqlite = { version = "0.28", features = ["bundled"]}
dirs = "4.0"